- .vscode/launch.json
- frontend/futureu-capstone/package-lock.json
- frontend/futureu-capstone/vite.config.js
> imported back tailwind to vite config

- backend/futureu/src/main/resources/application.properties
- frontend/futureu-capstone/src/components/AcademicExplorer.jsx
- Implemented adviser's suggestions for filter improvements:
- Removed school name filter option
- Added location search box functionality
- Changed filter title to 'FILTER BY'
- Used checkboxes for multiple filtering options
- Improved overall design with better spacing, shadows, and borders
- Updated filter system to allow location-based filtering without program selection
- Added toast notification for showing number of schools found
> Implemented suggestions for filter function

- backend/futureu/src/main/java/edu/cit/futureu/entity/AssessmentCategoryEntity.java
- backend/futureu/src/main/java/edu/cit/futureu/entity/AssessmentEntity.java
- backend/futureu/src/main/java/edu/cit/futureu/entity/AssessmentSubCategoryEntity.java
- backend/futureu/src/main/java/edu/cit/futureu/entity/ChoiceEntity.java
- backend/futureu/src/main/java/edu/cit/futureu/entity/QuestionEntity.java
- backend/futureu/src/main/java/edu/cit/futureu/entity/QuizSubCategoryCategoryEntity.java
- frontend/futureu-capstone/src/App.jsx
- frontend/futureu-capstone/src/config/apiConfig.js
- frontend/futureu-capstone/src/pages/AssessmentCategories.jsx
- frontend/futureu-capstone/src/pages/AssessmentSubCategories.jsx
- frontend/futureu-capstone/src/pages/Assessments.jsx
- frontend/futureu-capstone/src/pages/Questions.jsx
- frontend/futureu-capstone/src/pages/QuizSubCategories.jsx
- frontend/futureu-capstone/src/services/api.js
- frontend/futureu-capstone/src/services/assessmentCategoryService.js
- frontend/futureu-capstone/src/services/assessmentService.js
- frontend/futureu-capstone/src/services/assessmentSubCategoryService.js
- frontend/futureu-capstone/src/services/choiceService.js
- frontend/futureu-capstone/src/services/questionService.js
- frontend/futureu-capstone/src/services/quizSubCategoryCategoryService.js
Now with BaseURL (wa pa naapply sa previous api calls)
base apiClient (wa pa sad naapply sa previous api calls)
dedicated services for the endpoints (api calls)
- assessment
- assessmentCategory
- assessmentSubCategory
- quizSubCategoryCategory
- question
- choice
added JsonAnnotations
@JsonManageReference for ManyToOne annotation
@JsonBackReference for OneToMany annotation
Added dedicated pages for the entities.
Kind of like A management page (For admin's view nalang sad ni) gatry2 raman ta ko if makafetch ba kos records nya nindut naman output, need for more actions nlang and layouting.
> Scalable and Reusable API Calls

- backend/futureu/src/main/resources/application.properties
- frontend/futureu-capstone/src/components/AcademicExplorer.jsx
-When user selects a specific program, a detailed description about that program will pop up
-Changed the virtual tour button in the individual school cards to view more
-Clicking view more button will show a detailed description about the school
- The selected program of the user will be displayed and the detailed description of the program is placed in the left panel
- Added background pictures in school comparison
-Enhanced the layout of the school comparison
-For each individual school card in school comparison, I included school location, school type, school description and the number of programs offered
-Modified the filter function it now includes a filter for school type using radio buttons
-Added welcome modal with intuitive onboarding instructions
-Fixed Programs dropdown …
> responsive animations and dynamic container adjustments

- backend/futureu/src/main/resources/application.properties
- frontend/futureu-capstone/package-lock.json
- frontend/futureu-capstone/package.json
- frontend/futureu-capstone/src/App.css
- frontend/futureu-capstone/src/App.jsx
- frontend/futureu-capstone/src/components/Assessment/AssessmentSection.jsx
- frontend/futureu-capstone/src/components/Assessment/QuestionItem.jsx
- frontend/futureu-capstone/src/components/Assessment/SectionNavigator.jsx
- frontend/futureu-capstone/src/pages/Questions.jsx
- frontend/futureu-capstone/src/pages/TakeAssessment.jsx
- frontend/futureu-capstone/src/services/assessmentTakingService.js
- frontend/futureu-capstone/src/styles/animations.css
wala na checkout new branch HAHAHA
Unsay naadd?
Frontend:
everything from Assessment Folder
TakeAssessment.jsx inside pages folder
Animations.css
AssessmentTakingService.js inside services folder
Loading animation cute HAHA
nara sa commits descriptions most of the additions.
> Take Assessment

- frontend/futureu-capstone/package-lock.json
- frontend/futureu-capstone/package.json
- frontend/futureu-capstone/src/components/AcademicExplorer.jsx
- frontend/futureu-capstone/src/components/UserLandingPage.jsx
- frontend/futureu-capstone/src/components/VirtualCampusToursPage.jsx
- Modified the left panel(program description) in the academic explorer
- Left align the school descriptions in the pop up
- Enhanced the design and layout of the virtual campus tours and added animations
- Added a search bar function in the virtual campus tours
- Enhanced the design and layout in the user landing page
- Added the initial design of module 4(alumni and student reviews)
- Added animations in the user landing page
> Adjustment

- backend/futureu/pom.xml
- backend/futureu/src/main/java/edu/cit/futureu/config/SecurityConfig.java
- backend/futureu/src/main/java/edu/cit/futureu/config/WebConfig.java
- backend/futureu/src/main/java/edu/cit/futureu/controller/AuthController.java
- backend/futureu/src/main/java/edu/cit/futureu/dto/JwtResponse.java
- backend/futureu/src/main/java/edu/cit/futureu/dto/SigninRequest.java
- backend/futureu/src/main/java/edu/cit/futureu/dto/SignupRequest.java
- backend/futureu/src/main/java/edu/cit/futureu/entity/Role.java
- backend/futureu/src/main/java/edu/cit/futureu/jwt/AuthEntryPointJwt.java
- backend/futureu/src/main/java/edu/cit/futureu/jwt/AuthTokenFilter.java
- backend/futureu/src/main/java/edu/cit/futureu/jwt/JwtUtil.java
- backend/futureu/src/main/java/edu/cit/futureu/service/UserDetailsServiceImpl.java
- backend/futureu/src/main/resources/application.properties
- frontend/futureu-capstone/src/App.jsx
- frontend/futureu-capstone/src/components/Authentication/StudentLogin.jsx
- frontend/futureu-capstone/src/components/Authentication/StudentRegister.jsx
- frontend/futureu-capstone/src/services/api.js
- frontend/futureu-capstone/src/services/authService.js
-Added Login Register for User
-Defaults to Studenr Role
-Used JWT
-Routing is not implemented
> rbac-setup

- frontend/futureu-capstone/src/components/Assessment/AssessmentSection.jsx
- frontend/futureu-capstone/src/components/Assessment/SectionNavigator.jsx
- frontend/futureu-capstone/src/pages/TakeAssessment.jsx
a. Make the assessment 5 questions per page to reduce clicking NEXT button several times.
b. Put a timer in assessment to enable users to see their elapsed time.
c. Improve UI for the assessment subcategory (e.g., GSA, AT) and assessment subcategory subcategories (e.g., SA, RC, STEM, R, I, etc.) for more readability.
> Mod 5 at 6

- backend/futureu/src/main/java/edu/cit/futureu/config/SecurityConfig.java
- backend/futureu/src/main/java/edu/cit/futureu/controller/WebTest.java
- backend/futureu/src/main/java/edu/cit/futureu/jwt/JwtUtil.java
- backend/futureu/src/main/resources/application.properties
- frontend/futureu-capstone/src/App.jsx
- frontend/futureu-capstone/src/components/AcademicExplorer.jsx
- frontend/futureu-capstone/src/components/PrivateRoute.jsx
- frontend/futureu-capstone/src/components/VirtualCampusToursPage.jsx
frontend authentication header bearer token
> frontend authentication header bearer token

- backend/futureu/src/main/resources/application.properties
- frontend/futureu-capstone/package-lock.json
- frontend/futureu-capstone/package.json
- frontend/futureu-capstone/src/App.jsx
- frontend/futureu-capstone/src/components/Navigation.jsx
- frontend/futureu-capstone/src/components/PublicRoute.jsx
- frontend/futureu-capstone/src/components/VirtualCampusToursPage.jsx
-Defaults to Landing Page
-Requires Sign-in or Sign-up
-Fixed CareerPathWays Loop
-Dynamic NavBar
> fix-paras-v1

- frontend/futureu-capstone/.vite/deps/_metadata.json
- frontend/futureu-capstone/.vite/deps/package.json
- frontend/futureu-capstone/package-lock.json
- frontend/futureu-capstone/package.json
- frontend/futureu-capstone/src/App.jsx
- frontend/futureu-capstone/src/components/Navigation.jsx
- frontend/futureu-capstone/src/components/SchoolsPage.jsx
- frontend/futureu-capstone/src/main.jsx
Initial Design for SchoolsPage Testimonials Feature
- Added Leafleat.Js
- Integrated OpenStreetsMap
> Initial Design for SchoolsPage Testimonials Feature

- backend/futureu/src/main/java/edu/cit/futureu/controller/TestimonyController.java
- backend/futureu/src/main/java/edu/cit/futureu/entity/SchoolEntity.java
- backend/futureu/src/main/java/edu/cit/futureu/entity/TestimonyEntity.java
- backend/futureu/src/main/java/edu/cit/futureu/entity/UserEntity.java
- backend/futureu/src/main/java/edu/cit/futureu/service/TestimonyService.java
- frontend/futureu-capstone/src/components/Testimonials.jsx
- frontend/futureu-capstone/src/components/testimonials/SchoolsSection.jsx
- frontend/futureu-capstone/src/components/testimonials/TestimonialCard.jsx
- frontend/futureu-capstone/src/components/testimonials/TestimonialForm.jsx
- frontend/futureu-capstone/src/components/testimonials/TestimonialHero.jsx
- frontend/futureu-capstone/src/services/testimonialService.js
- CRUD functionality for the testimony
- Added a form for creating and editing a testimony
- Added a rating attribute in backend
- Users can rate a school from 1- 5 upon fill up in the form
- total reviews per school are displayed
- average rating per school are displayed in schools sections card
- Added a background picture per school card
- Added a search bar function
- Added logo and background pictures of schools in reviews tab
- Successfully fetched and displayed the firstname, lastname, school name once the review is submitted
-Added dynamic buttons for adding a review
> testimonials

- backend/futureu/src/main/java/edu/cit/futureu/entity/SchoolEntity.java
- frontend/futureu-capstone/src/components/CesiumSchoolsGlobe.jsx
- frontend/futureu-capstone/src/components/VirtualCampusToursPage.jsx
Improved the Map Integration and its UI in Virtual Campus Tours Page
> Improved the Map Integration and its UI in Virtual Campus Tours Page

- backend/futureu/src/main/java/edu/cit/futureu/config/SecurityConfig.java
- backend/futureu/src/main/resources/application.properties
- frontend/futureu-capstone/src/App.jsx
- frontend/futureu-capstone/src/components/Admin/AdminDashboardTest.jsx
- frontend/futureu-capstone/src/components/Admin/AdminLogin.jsx
- frontend/futureu-capstone/src/components/Admin/Unauthorized.jsx
- frontend/futureu-capstone/src/components/AdminRoute.jsx
- frontend/futureu-capstone/src/components/Navigation.jsx
- frontend/futureu-capstone/src/services/authService.js
-Backend: APIs can now be accessed as long as user is Authenticated/Authorized
-RBAC is done in Frontend
-To create admin (for now), create user and change role in workbench to ADMIN
> fix-rbac-paras-v1

- backend/futureu/src/main/java/edu/cit/futureu/controller/AccreditationController.java
- backend/futureu/src/main/java/edu/cit/futureu/entity/AccreditationEntity.java
- backend/futureu/src/main/java/edu/cit/futureu/entity/TestimonyEntity.java
- backend/futureu/src/main/java/edu/cit/futureu/repository/AccreditationRepository.java
- backend/futureu/src/main/java/edu/cit/futureu/service/AccreditationService.java
- backend/futureu/src/main/resources/application.properties
- frontend/futureu-capstone/src/components/AcademicExplorer.jsx
- frontend/futureu-capstone/src/components/AccreditationRatings.jsx
- frontend/futureu-capstone/src/components/accreditation/FilterOptions.jsx
- frontend/futureu-capstone/src/components/accreditation/tabs/ProgramsTab.jsx
- frontend/futureu-capstone/src/components/testimonials/SchoolsSection.jsx
- frontend/futureu-capstone/src/components/testimonials/TestimonialCard.jsx
- frontend/futureu-capstone/src/components/testimonials/TestimonialForm.jsx
- frontend/futureu-capstone/src/services/accreditationService.js
- frontend/futureu-capstone/src/services/schoolProgramService.js
- Modified the search function in academic explorer, when searching a specific school it displays all programs offered
- Remove the mock data/hard coded data for the accreditation
- Fixed the unauthorized error in accreditation
- Accreditation can fetch inserted data in the database
- Modified the filter function in accreditation
- Displays the program name, school name, accreditation status, accrediting body, and recognition
- Added the program_id field to the accreditation classes in the backend to establish a direct relationship between programs and their accreditations
- Modified Backend Files:
-Accreditation Controller
-Accreditation Repo
-Accreditation Service
-Accreditation Entity
> Fixed unauthorized error in accreditation and search function in academic explorer

- backend/futureu/src/main/java/edu/cit/futureu/controller/CareerController.java
- backend/futureu/src/main/java/edu/cit/futureu/entity/AssessmentCategoryEntity.java
- backend/futureu/src/main/java/edu/cit/futureu/entity/AssessmentSubCategoryEntity.java
- backend/futureu/src/main/java/edu/cit/futureu/entity/CareerEntity.java
- backend/futureu/src/main/java/edu/cit/futureu/entity/CareerProgramEntity.java
- backend/futureu/src/main/java/edu/cit/futureu/entity/ChoiceEntity.java
- backend/futureu/src/main/java/edu/cit/futureu/entity/QuestionEntity.java
- backend/futureu/src/main/java/edu/cit/futureu/entity/QuizSubCategoryCategoryEntity.java
- backend/futureu/src/main/java/edu/cit/futureu/service/QuestionService.java
- backend/futureu/src/main/java/edu/cit/futureu/service/UserService.java
- frontend/futureu-capstone/src/components/Admin/AdminDashboard.jsx
- frontend/futureu-capstone/src/components/Admin/CRUD_Accreditation.jsx
- frontend/futureu-capstone/src/components/Admin/CRUD_AssessmentCategory.jsx
- frontend/futureu-capstone/src/components/Admin/CRUD_Career.jsx
- frontend/futureu-capstone/src/components/Admin/CRUD_Choice.jsx
- frontend/futureu-capstone/src/components/Admin/CRUD_Program.jsx
- frontend/futureu-capstone/src/components/Admin/CRUD_Question.jsx
- frontend/futureu-capstone/src/components/Admin/CRUD_User.jsx
- frontend/futureu-capstone/src/services/adminCareerService.js
- frontend/futureu-capstone/src/services/adminChoiceService.js
- frontend/futureu-capstone/src/services/adminQuestionService.js
- frontend/futureu-capstone/src/services/adminQuizSubCatService.js
Admin Dashboard & Authentication Fixes
Entity Relationships:
-     Removed @JsonBackReference from AssessmentCategoryEntity, AssessmentSubCategoryEntity, QuizSubCategoryCategoryEntity, ChoiceEntity to fix N/A values in admin tables
-     Fixed parent-child data relationships for proper display in admin dashboards
-     Authentication & User Management:
-     Fixed student registration by preventing password double-encryption
-     Added password encoding detection to UserService
-     Resolved "bad credentials" error in student login process when a new user is created directly in the admin dashboard(CRUD_User)
Frontend Improvements:
- improved design and layout of CRUD_Accreditation, program, user, and admin dashboard
- Updated adminChoiceService to properly format API requests
- Modified …
> admin dashboard and fixes

- backend/futureu/src/main/resources/application.properties
- frontend/futureu-capstone/src/components/AccreditationRatings.jsx
- frontend/futureu-capstone/src/components/accreditation/CompareSchools.jsx
- frontend/futureu-capstone/src/components/accreditation/FilterOptions.jsx
- frontend/futureu-capstone/src/components/accreditation/GuideModal.jsx
- frontend/futureu-capstone/src/components/accreditation/ProgramDetailsModal.jsx
- frontend/futureu-capstone/src/components/accreditation/ProgramsModal.jsx
- frontend/futureu-capstone/src/components/accreditation/SchoolCard.jsx
- frontend/futureu-capstone/src/components/accreditation/SchoolsList.jsx
- frontend/futureu-capstone/src/components/accreditation/StatsCards.jsx
- frontend/futureu-capstone/src/services/accreditationService.js
-Fixed SchoolCard component
-Added proper handling for school backgrounds and logos
- Added schools tab
- Added a compare schools feature
-Enhanced Compare Schools Modal
- Adjusted container spacing for better readability
- Improved school card layouts
- Made school logos and background images display properly
- Improved Program Details Modal
- Added school background images and logos
- Enhanced Tab Navigation:
- Consistent styling across all modals
- Better spacing and alignment
- Enhanced visual hierarchy
- Improved accessibility
- Added smooth transitions and animations
> Enhance Module 2 Accreditation features and UI

- backend/futureu/src/main/java/edu/cit/futureu/service/UserAssessmentService.java
- frontend/futureu-capstone/src/components/Assessment/SectionNavigator.jsx
- frontend/futureu-capstone/src/components/tabs/RecommendationsTab.jsx
- frontend/futureu-capstone/src/pages/TakeAssessment.jsx
- frontend/futureu-capstone/src/styles/animations.css
save user assessment when completing submission
not just on save & exit use case
> Submit assessment

- backend/futureu/src/main/resources/application.properties
- frontend/futureu-capstone/src/pages/Questions.jsx
Edit choice and question in the questions page/tab (Admin Side)
> edit choices and questions sa question management in the Admin side

- backend/futureu/src/main/java/edu/cit/futureu/config/SecurityConfig.java
- backend/futureu/src/main/java/edu/cit/futureu/controller/UserController.java
- backend/futureu/src/main/resources/application.properties
- frontend/futureu-capstone/src/App.jsx
- frontend/futureu-capstone/src/components/Authentication/StudentLogin.jsx
- frontend/futureu-capstone/src/components/Navigation.jsx
- frontend/futureu-capstone/src/components/Student/StudentHomepage.jsx
- frontend/futureu-capstone/src/components/UserLandingPage.jsx
- frontend/futureu-capstone/src/components/routes/PublicRoute.jsx
- frontend/futureu-capstone/src/index.css
- frontend/futureu-capstone/src/services/api.js
- frontend/futureu-capstone/src/services/statisticsService.js
feat: redesign Student Home hero 
fix: remove global button overrides in index.css so Tailwind brand colors apply
feat: redesign Your Assessment Overview
feat: expand dashboard sections to full width; align spacing with other sections
feat(: redesign “Exploration Tools” cards (white cards, gradient icon tiles, arrow), add “Discover More” button linking to Academic Explorer
style left-align text in action cards, assessment rows, and exploration cards for consistency
feat(backend): allow public GET access for testimonials and school programs; add GET /api/user/public/countStudents
refactor(frontend): use public student count endpoint in statisticsService
> feat_student_home

- frontend/futureu-capstone/src/components/AcademicExplorer.jsx
…mponents and caching.
Successfully debugged the errors in AcademicExplorer.jsx after merging reusable components and caching.
> Debugged the errors in AcademicExplorer.jsx

- backend/futureu/src/main/resources/application.properties
- frontend/futureu-capstone/src/components/Testimonials.jsx
- frontend/futureu-capstone/src/components/UserLandingPage.jsx
- frontend/futureu-capstone/src/components/testimonials/SchoolsSection.jsx
- frontend/futureu-capstone/src/components/testimonials/TestimonialCard.jsx
- frontend/futureu-capstone/src/components/testimonials/TestimonialForm.jsx
- frontend/futureu-capstone/src/services/testimonialService.js
- Fixed the data structure mismatch
- Added a wrapper for testimonial functions(average ratings and total reviews)
- Fixed the 0 rating display in individual school cards
- Modified User Landing page to properly fetch and display submitted testimonials
- Cache clearing
- Added proper cache clearing for school ratings and display
> Fix testimonials

- backend/futureu/src/main/resources/application.properties
- frontend/futureu-capstone/src/components/Assessment/AssessmentSection.jsx
- frontend/futureu-capstone/src/components/Assessment/QuestionItem.jsx
Newlines are preserved in the verbal ability section.
Enforced a rule to underline words and only questions that actually request an underlined/emphasized word will show an underline.
> fix: assessment issues
